DROP TABLE IF EXISTS posts;

CREATE TABLE todos(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user TEXT NOT NULL,
    item TEXT NOT NULL,
	priority INTEGER NOT NULL,
	completed BOOLEAN NOT NULL
);